version: '3.7'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432  

    environment:
      - POSTGRES_DB=flixDB
      - POSTGRES_USER=stark
      - POSTGRES_PASSWORD=starkdb05

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080